services:
  heplify:
    image: sipcapture/heplify:latest
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    command:
      # Replace this IP with the one for your heplify-server instance
      ./heplify -e -hs 192.168.1.29:9060 -m SIPRTCP -dd -zf -l info
    network_mode: host
    restart: unless-stopped