[sources.homer_scrape]
type = "prometheus_scrape"
endpoints = [ "http://heplify-server:9096/metrics" ]
scrape_interval_secs = 10
instance_tag = "heplify"
endpoint_tag = "homer"

[sinks.prom_write]
type = "prometheus_remote_write"
inputs = [ "homer_scrape" ]
endpoint = "http://qryn:3100/prom/remote/write"
